"""BLAZE Agent 3 — Tactical Fusion & Planning.

Correlates ordered ``RadioEvent`` objects, the ``SituationSnapshot``, unit state and
the road graph into a versioned :class:`DraftTacticalPlan` via the shared Gemma
client (``chat_structured``). The agent NEVER dispatches anything: it only drafts.

Deterministic post-LLM guardrails (applied in code, never delegated to the model):

1. every ``evidence_id`` must exist in the real inputs (RadioEvent ``event_id`` s or
   snapshot tool call ids) — unknown ids are removed and an uncertainty is added;
2. every ``unit_id`` in ``unit_actions`` must belong to a known unit — actions for
   unknown units are dropped and an uncertainty is added;
3. ``version`` is computed by code (``previous_plan.version + 1``), and ``plan_id`` /
   ``created_at`` are generated by code — whatever the LLM says is overwritten;
4. re-planning never mutates the previous plan; changed action ids are reported in
   :attr:`DraftTacticalPlan.changed_action_ids`;
5. ``human_approval_required`` is forced to ``True`` for high/critical priority;
6. the final plan is validated against ``contracts/schemas/draft_tactical_plan.schema.json``.

All plan versions are kept in an append-only in-memory :class:`PlanHistory`.
"""

from __future__ import annotations

import copy
import inspect
import json
import threading
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Callable, Iterable, Mapping, Sequence

import jsonschema
from referencing import Registry, Resource

from agents.common.inference_client import GemmaClient

REPO_ROOT = Path(__file__).resolve().parents[2]
PROMPT_PATH = REPO_ROOT / "inference" / "prompts" / "tactical_planning.md"
SCHEMA_DIR = REPO_ROOT / "contracts" / "schemas"
PLAN_SCHEMA_PATH = SCHEMA_DIR / "draft_tactical_plan.schema.json"
UNIT_ACTION_SCHEMA_PATH = SCHEMA_DIR / "unit_action.schema.json"

AGENT_NAME = "tactical_planning"

#: Priorities that always require explicit human approval (guardrail 5).
APPROVAL_FORCED_PRIORITIES = frozenset({"high", "critical"})

#: How many rounds of tool calls the agent may request before drafting the plan.
MAX_TOOL_ROUNDS = 2

#: Action fields compared to decide whether an action changed between plan versions.
_ACTION_COMPARE_FIELDS = (
    "unit_id",
    "action_type",
    "instruction",
    "route",
    "destination",
    "reason",
    "priority",
    "evidence_ids",
    "confidence",
    "human_approval_required",
    "acknowledgement_required",
)

#: OpenAI-format definition of the routing tool the LLM may request.
COMPUTE_ROUTE_TOOL: dict[str, Any] = {
    "type": "function",
    "function": {
        "name": "compute_route",
        "description": (
            "Compute a vehicle-compatible route on the incident road graph, avoiding "
            "blocked segments. Returns the selected route and rejected alternatives."
        ),
        "parameters": {
            "type": "object",
            "properties": {
                "origin": {"type": "string", "description": "Origin node or unit position id."},
                "destination": {"type": "string", "description": "Destination node id."},
                "vehicle_type": {
                    "type": "string",
                    "description": "Vehicle type (e.g. CCF, light_vehicle, command_post).",
                },
                "blocked_edges": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": "Road ids to avoid.",
                },
            },
            "required": ["origin", "destination", "vehicle_type"],
        },
    },
}

#: Schema the LLM is asked to satisfy. plan_id / version / created_at are optional
#: here on purpose: they are overwritten deterministically by the agent (guardrail 3).
LLM_RESPONSE_SCHEMA: dict[str, Any] = {
    "type": "object",
    "properties": {
        "summary": {"type": "string"},
        "objectives": {"type": "array", "items": {"type": "string"}},
        "unit_actions": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "unit_id": {"type": "string"},
                    "action_type": {"type": "string"},
                    "instruction": {"type": "string"},
                    "route": {"type": ["string", "null"]},
                    "destination": {"type": ["string", "null"]},
                    "reason": {"type": "string"},
                    "priority": {
                        "type": "string",
                        "enum": ["low", "medium", "high", "critical"],
                    },
                    "evidence_ids": {"type": "array", "items": {"type": "string"}},
                    "confidence": {"type": "number", "minimum": 0, "maximum": 1},
                    "human_approval_required": {"type": "boolean"},
                    "acknowledgement_required": {"type": "boolean"},
                },
                "required": [
                    "unit_id",
                    "action_type",
                    "instruction",
                    "reason",
                    "priority",
                    "evidence_ids",
                    "confidence",
                ],
            },
        },
        "rejected_options": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "option": {"type": "string"},
                    "reason": {"type": "string"},
                },
                "required": ["option", "reason"],
            },
        },
        "assumptions": {"type": "array", "items": {"type": "string"}},
        "uncertainties": {"type": "array", "items": {"type": "string"}},
        "evidence_ids": {"type": "array", "items": {"type": "string"}},
    },
    "required": ["summary", "objectives", "unit_actions"],
}


class DraftTacticalPlan(dict):
    """A schema-conformant DraftTacticalPlan.

    Behaves exactly like the plan ``dict`` (JSON-serializable, validates against
    ``draft_tactical_plan.schema.json``) with guardrail metadata attached:

    - :attr:`changed_action_ids` — action ids added, changed or removed relative to
      the previous plan version (empty tuple for version 1);
    - :attr:`guardrail_notes` — human-readable notes about deterministic corrections
      applied after the LLM call (removed evidence, dropped units, forced approvals).
    """

    changed_action_ids: tuple[str, ...] = ()
    guardrail_notes: tuple[str, ...] = ()

    def to_dict(self) -> dict[str, Any]:
        """Plain deep-copied dict view of the plan."""
        return copy.deepcopy(dict(self))


class PlanHistory:
    """Append-only, thread-safe in-memory store of every plan version.

    Plans are deep-copied on the way in and on the way out so no caller can mutate
    a stored version. Nothing is ever deleted or replaced.
    """

    def __init__(self) -> None:
        self._lock = threading.Lock()
        self._plans: list[dict[str, Any]] = []

    def append(self, plan: Mapping[str, Any]) -> None:
        with self._lock:
            self._plans.append(copy.deepcopy(dict(plan)))

    def __len__(self) -> int:
        with self._lock:
            return len(self._plans)

    def versions(self) -> tuple[int, ...]:
        with self._lock:
            return tuple(p["version"] for p in self._plans)

    def all(self) -> tuple[dict[str, Any], ...]:
        with self._lock:
            return tuple(copy.deepcopy(p) for p in self._plans)

    def get_version(self, version: int) -> dict[str, Any] | None:
        with self._lock:
            for plan in self._plans:
                if plan.get("version") == version:
                    return copy.deepcopy(plan)
        return None

    def latest(self) -> dict[str, Any] | None:
        with self._lock:
            return copy.deepcopy(self._plans[-1]) if self._plans else None


def load_plan_validator() -> jsonschema.Draft7Validator:
    """Validator for the real contract schema, with the unit_action $ref resolved."""
    plan_schema = json.loads(PLAN_SCHEMA_PATH.read_text(encoding="utf-8"))
    unit_action_schema = json.loads(UNIT_ACTION_SCHEMA_PATH.read_text(encoding="utf-8"))
    registry = Registry().with_resources(
        [
            (plan_schema["$id"], Resource.from_contents(plan_schema)),
            (unit_action_schema["$id"], Resource.from_contents(unit_action_schema)),
        ]
    )
    return jsonschema.Draft7Validator(plan_schema, registry=registry)


def _collect_tool_call_ids(node: Any) -> set[str]:
    """Recursively collect tool call ids from a snapshot-like structure.

    Picks up any string under a ``tool_call_id`` key and any string items of a
    ``tool_call_ids`` list, wherever they appear in the snapshot.
    """
    found: set[str] = set()
    if isinstance(node, Mapping):
        for key, value in node.items():
            if key == "tool_call_id" and isinstance(value, str):
                found.add(value)
            elif key == "tool_call_ids" and isinstance(value, list):
                found.update(v for v in value if isinstance(v, str))
            else:
                found.update(_collect_tool_call_ids(value))
    elif isinstance(node, list):
        for item in node:
            found.update(_collect_tool_call_ids(item))
    return found


def _normalize_units(units: Any) -> list[dict[str, Any]]:
    """Accept either a plain list of unit dicts or a scenario file dict with 'units'."""
    if isinstance(units, Mapping) and "units" in units:
        units = units["units"]
    return [dict(u) for u in units]


class TacticalPlanningAgent:
    """Agent 3 — fuses radio intelligence + situation context into a draft plan.

    Parameters
    ----------
    client:
        Shared :class:`GemmaClient` (local vLLM). ``chat_structured`` is used for
        the plan itself; plain ``chat`` is used for the optional tool round(s).
    tool_executor:
        Optional callable ``(tool_name, arguments) -> result`` (sync or async) used
        to satisfy ``compute_route`` requests from the model. When ``None`` the tool
        is not offered.

    The agent only ever DRAFTS plans. It has no dispatch capability by design.
    """

    def __init__(
        self,
        client: GemmaClient,
        tool_executor: Callable[[str, dict[str, Any]], Any] | None = None,
    ) -> None:
        self.client = client
        self.tool_executor = tool_executor
        self.history = PlanHistory()
        self._system_prompt = PROMPT_PATH.read_text(encoding="utf-8")
        self._validator = load_plan_validator()

    # ------------------------------------------------------------------ public

    async def draft_plan(
        self,
        radio_events: Sequence[Mapping[str, Any]],
        snapshot: Mapping[str, Any],
        units: Any,
        previous_plan: Mapping[str, Any] | None = None,
    ) -> DraftTacticalPlan:
        """Draft the next tactical plan version. Never dispatches anything.

        ``radio_events`` must be chronologically ordered RadioEvent dicts,
        ``snapshot`` a SituationSnapshot dict, ``units`` the known unit states
        (list of dicts, or a scenario dict with a ``units`` key). When
        ``previous_plan`` is given the result is version ``previous + 1`` and the
        previous plan object is never mutated.
        """
        unit_list = _normalize_units(units)
        known_unit_ids = {u["unit_id"] for u in unit_list if "unit_id" in u}
        valid_evidence_ids = self._valid_evidence_ids(radio_events, snapshot)
        previous_copy = copy.deepcopy(dict(previous_plan)) if previous_plan is not None else None

        messages = self._build_messages(radio_events, snapshot, unit_list, previous_copy)
        if self.tool_executor is not None:
            messages, tool_ids = await self._run_tool_rounds(messages)
            valid_evidence_ids |= tool_ids

        result = await self.client.chat_structured(
            messages,
            schema=LLM_RESPONSE_SCHEMA,
            schema_name="draft_tactical_plan",
            agent=AGENT_NAME,
        )
        raw_plan = dict(result.data)

        plan = self._apply_guardrails(
            raw_plan,
            snapshot=snapshot,
            known_unit_ids=known_unit_ids,
            valid_evidence_ids=valid_evidence_ids,
            previous_plan=previous_copy,
        )
        self._validator.validate(dict(plan))  # guardrail 6 — real contract schema
        self.history.append(plan)
        return plan

    # ------------------------------------------------------------- LLM plumbing

    def _build_messages(
        self,
        radio_events: Sequence[Mapping[str, Any]],
        snapshot: Mapping[str, Any],
        units: list[dict[str, Any]],
        previous_plan: dict[str, Any] | None,
    ) -> list[dict[str, Any]]:
        def block(title: str, payload: Any) -> str:
            return f"{title}:\n{json.dumps(payload, ensure_ascii=False, indent=2)}"

        parts = [
            block("RADIO_EVENTS (chronological)", list(radio_events)),
            block("SITUATION_SNAPSHOT", dict(snapshot)),
            block("UNITS", units),
            block("ROAD_GRAPH", snapshot.get("roads", [])),
        ]
        if previous_plan is not None:
            parts.append(block("PREVIOUS_PLAN", previous_plan))
            parts.append(
                "Produce the NEXT revision of this plan. Keep still-valid actions, "
                "change only what the new events justify."
            )
        else:
            parts.append("Produce the initial draft tactical plan (version 1).")
        return [
            {"role": "system", "content": self._system_prompt},
            {"role": "user", "content": "\n\n".join(parts)},
        ]

    async def _run_tool_rounds(
        self, messages: list[dict[str, Any]]
    ) -> tuple[list[dict[str, Any]], set[str]]:
        """Offer compute_route; execute requested calls and append results."""
        messages = list(messages)
        executed_ids: set[str] = set()
        for _ in range(MAX_TOOL_ROUNDS):
            response = await self.client.chat(
                messages,
                tools=[COMPUTE_ROUTE_TOOL],
                tool_choice="auto",
                agent=AGENT_NAME,
            )
            if not response.tool_calls:
                break
            messages.append(
                {
                    "role": "assistant",
                    "content": response.content or "",
                    "tool_calls": [
                        {
                            "id": tc.id,
                            "type": "function",
                            "function": {
                                "name": tc.name,
                                "arguments": json.dumps(tc.arguments, ensure_ascii=False),
                            },
                        }
                        for tc in response.tool_calls
                    ],
                }
            )
            for tc in response.tool_calls:
                outcome = self.tool_executor(tc.name, tc.arguments)  # type: ignore[misc]
                if inspect.isawaitable(outcome):
                    outcome = await outcome
                if tc.id:
                    executed_ids.add(tc.id)
                messages.append(
                    {
                        "role": "tool",
                        "tool_call_id": tc.id,
                        "content": json.dumps(outcome, ensure_ascii=False, default=str),
                    }
                )
        return messages, executed_ids

    # -------------------------------------------------------------- guardrails

    @staticmethod
    def _valid_evidence_ids(
        radio_events: Sequence[Mapping[str, Any]], snapshot: Mapping[str, Any]
    ) -> set[str]:
        """Real ids evidence may point to: radio event ids + snapshot tool call ids."""
        valid: set[str] = set()
        for event in radio_events:
            event_id = event.get("event_id")
            if isinstance(event_id, str):
                valid.add(event_id)
        for event_id in snapshot.get("radio_events", []) or []:
            if isinstance(event_id, str):
                valid.add(event_id)
        valid |= _collect_tool_call_ids(snapshot)
        return valid

    def _apply_guardrails(
        self,
        raw_plan: dict[str, Any],
        *,
        snapshot: Mapping[str, Any],
        known_unit_ids: set[str],
        valid_evidence_ids: set[str],
        previous_plan: dict[str, Any] | None,
    ) -> DraftTacticalPlan:
        notes: list[str] = []
        uncertainties: list[str] = [
            u for u in raw_plan.get("uncertainties", []) if isinstance(u, str)
        ]

        def add_uncertainty(text: str) -> None:
            if text not in uncertainties:
                uncertainties.append(text)
            if text not in notes:
                notes.append(text)

        # Guardrail 1+2 — evidence ids must be real, unit ids must be known.
        actions: list[dict[str, Any]] = []
        for raw_action in raw_plan.get("unit_actions", []):
            action = dict(raw_action)
            unit_id = action.get("unit_id")
            if unit_id not in known_unit_ids:
                add_uncertainty(
                    f"Discarded a proposed action for unknown unit '{unit_id}': "
                    "not part of the engaged units."
                )
                continue

            kept_evidence: list[str] = []
            for evidence_id in action.get("evidence_ids", []):
                if evidence_id in valid_evidence_ids:
                    if evidence_id not in kept_evidence:
                        kept_evidence.append(evidence_id)
                else:
                    add_uncertainty(
                        f"Removed unverifiable evidence id '{evidence_id}' "
                        f"(unit '{unit_id}'): it does not match any provided "
                        "radio event or tool call."
                    )
            action["evidence_ids"] = kept_evidence
            if not kept_evidence:
                add_uncertainty(
                    f"Action for unit '{unit_id}' has no remaining verifiable evidence."
                )

            # Guardrail 5 — forced human approval for high/critical priorities.
            priority = action.get("priority")
            forced = priority in APPROVAL_FORCED_PRIORITIES
            if forced and action.get("human_approval_required") is not True:
                notes.append(
                    f"Forced human_approval_required=true for {priority}-priority "
                    f"action on unit '{unit_id}'."
                )
            action["human_approval_required"] = (
                True if forced else bool(action.get("human_approval_required", True))
            )
            action.setdefault("acknowledgement_required", forced)
            action.setdefault("route", None)
            action.setdefault("destination", None)
            actions.append(action)

        # Plan-level evidence: filter the same way, then ensure it covers actions.
        plan_evidence: list[str] = []
        for evidence_id in raw_plan.get("evidence_ids", []):
            if evidence_id in valid_evidence_ids:
                if evidence_id not in plan_evidence:
                    plan_evidence.append(evidence_id)
            else:
                add_uncertainty(
                    f"Removed unverifiable plan-level evidence id '{evidence_id}'."
                )
        for action in actions:
            for evidence_id in action["evidence_ids"]:
                if evidence_id not in plan_evidence:
                    plan_evidence.append(evidence_id)

        # Flag unresolved snapshot conflicts (never silently resolved).
        for conflict in snapshot.get("conflicts", []) or []:
            if isinstance(conflict, str):
                flagged = f"Unresolved conflict: {conflict}"
                if conflict not in uncertainties and flagged not in uncertainties:
                    uncertainties.append(flagged)

        # Guardrail 3 — version / plan_id / created_at are code-generated.
        version = int(previous_plan["version"]) + 1 if previous_plan else 1
        incident_id = str(
            snapshot.get("incident_id")
            or (previous_plan or {}).get("incident_id")
            or "unknown-incident"
        )

        # Guardrail 4 — stable action ids vs previous plan, previous never mutated.
        changed_action_ids = self._assign_action_ids(actions, previous_plan, version)

        plan = DraftTacticalPlan(
            plan_id=f"plan-v{version}-{uuid.uuid4().hex[:8]}",
            incident_id=incident_id,
            version=version,
            summary=str(raw_plan.get("summary", "")),
            objectives=[o for o in raw_plan.get("objectives", []) if isinstance(o, str)],
            unit_actions=actions,
            rejected_options=[
                {"option": str(r.get("option", "")), "reason": str(r.get("reason", ""))}
                for r in raw_plan.get("rejected_options", [])
                if isinstance(r, Mapping)
            ],
            assumptions=[a for a in raw_plan.get("assumptions", []) if isinstance(a, str)],
            uncertainties=uncertainties,
            evidence_ids=plan_evidence,
            created_at=datetime.now(timezone.utc).isoformat().replace("+00:00", "Z"),
        )
        plan.changed_action_ids = tuple(changed_action_ids)
        plan.guardrail_notes = tuple(notes)
        return plan

    @staticmethod
    def _assign_action_ids(
        actions: list[dict[str, Any]],
        previous_plan: dict[str, Any] | None,
        version: int,
    ) -> list[str]:
        """Assign deterministic action ids; return ids changed vs the previous plan.

        An action identical (all compared fields) to the previous action for the
        same unit keeps its previous ``action_id``. Anything added or modified gets
        a fresh id and is reported as changed; actions that disappeared are also
        reported as changed (their old ids).
        """
        previous_actions: dict[str, dict[str, Any]] = {}
        if previous_plan:
            for prev in previous_plan.get("unit_actions", []):
                if isinstance(prev, Mapping) and "unit_id" in prev:
                    previous_actions[prev["unit_id"]] = dict(prev)

        changed: list[str] = []
        counter = 1
        seen_units: set[str] = set()
        for action in actions:
            unit_id = action["unit_id"]
            seen_units.add(unit_id)
            prev = previous_actions.get(unit_id)
            if prev is not None and all(
                action.get(field) == prev.get(field) for field in _ACTION_COMPARE_FIELDS
            ):
                action["action_id"] = prev.get("action_id") or f"ua-{version * 100 + counter}"
            else:
                action["action_id"] = f"ua-{version * 100 + counter}"
                changed.append(action["action_id"])
            counter += 1

        for unit_id, prev in previous_actions.items():
            if unit_id not in seen_units and prev.get("action_id"):
                changed.append(prev["action_id"])  # action removed in this version
        return changed


__all__ = [
    "AGENT_NAME",
    "COMPUTE_ROUTE_TOOL",
    "DraftTacticalPlan",
    "LLM_RESPONSE_SCHEMA",
    "PlanHistory",
    "TacticalPlanningAgent",
    "load_plan_validator",
]
